
RES_PATH = './res/'

#MainWindow
WINDOW_QSS = RES_PATH + "theme.qss"
WINDOW_ICON = RES_PATH + "win.png"
WINDOW_TITLE = "摄像头芯片AI测试套件"

WINDOW_DEFAULT_WIDTH = 800
WINDOW_DEFAULT_HEIGHT = 600
Control_HEIGHT = "50px"
PaddingLR = 20
#title bar
TITLE_BAR_HEIGHT = 40
TITLE_BUTTON_SIZE = 25
TITLE_LABEL_SIZE = 20
TITLE_BUTTON_WIDTH = 30
TITLE_BUTTON_HEIGHT = 30
TITLE_ICON_MAG = 14
HISTORY_LABELS_SIZE = 30

TITLE_MIN_ICON = RES_PATH + "min.png"
TITLE_SEARCH_ICON = RES_PATH + "search.png"
TITLE_HISTORY_ICON = RES_PATH + "lsjl.png"
TITLE_CLS_ICON = RES_PATH + "exit.png"
TITLE_RESTORE_ICON = RES_PATH + "restore.png"

